[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["mvn package -DskipTests"]


[phases.install]
cmds = ["mvn clean install -DskipTests"]

[start]
cmd = "java -jar target/finance-tracker-backend-1.0.0.jar"
