/** Canonical authenticated routes and stable root `data-testid` from page shells. */
export const AUTHENTICATED_APP_ROUTE_ROOTS = [
  { path: '/app/dashboard', testId: 'page-dashboard' },
  { path: '/app/transactions', testId: 'page-transactions' },
  { path: '/app/accounts', testId: 'page-accounts' },
  { path: '/app/budgets', testId: 'page-budgets' },
  { path: '/app/savings', testId: 'page-savings' },
  { path: '/app/recurring', testId: 'page-recurring' },
  { path: '/app/loans', testId: 'page-loans' },
  { path: '/app/networth', testId: 'page-networth' },
  { path: '/app/health', testId: 'page-health' },
  { path: '/app/carbon', testId: 'page-carbon' },
  { path: '/app/categories', testId: 'page-categories' },
  { path: '/app/insights', testId: 'page-insights' },
  { path: '/app/income', testId: 'page-income' },
  { path: '/app/review', testId: 'page-review' },
  { path: '/app/investments', testId: 'page-investments' },
  { path: '/app/forecasting', testId: 'page-forecasting' },
  { path: '/app/tax', testId: 'page-tax' },
  { path: '/app/reports', testId: 'page-reports' },
  { path: '/app/audit', testId: 'page-audit' },
  { path: '/app/family', testId: 'page-family' },
  { path: '/app/settings', testId: 'page-settings' },
] as const;
